// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: primesapi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimesApiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PrimesApiRequest) Reset() {
	*x = PrimesApiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primesapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimesApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimesApiRequest) ProtoMessage() {}

func (x *PrimesApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_primesapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimesApiRequest.ProtoReflect.Descriptor instead.
func (*PrimesApiRequest) Descriptor() ([]byte, []int) {
	return file_primesapi_proto_rawDescGZIP(), []int{0}
}

func (x *PrimesApiRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PrimesApiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prime int32 `protobuf:"varint,1,opt,name=prime,proto3" json:"prime,omitempty"`
}

func (x *PrimesApiResponse) Reset() {
	*x = PrimesApiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primesapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimesApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimesApiResponse) ProtoMessage() {}

func (x *PrimesApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_primesapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimesApiResponse.ProtoReflect.Descriptor instead.
func (*PrimesApiResponse) Descriptor() ([]byte, []int) {
	return file_primesapi_proto_rawDescGZIP(), []int{1}
}

func (x *PrimesApiResponse) GetPrime() int32 {
	if x != nil {
		return x.Prime
	}
	return 0
}

var File_primesapi_proto protoreflect.FileDescriptor

var file_primesapi_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x22, 0x2a, 0x0a,
	0x10, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x29, 0x0a, 0x11, 0x50, 0x72, 0x69,
	0x6d, 0x65, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x6d, 0x65, 0x32, 0x5b, 0x0a, 0x10, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x41, 0x50,
	0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x50, 0x72, 0x69, 0x6d,
	0x65, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72,
	0x69, 0x6d, 0x65, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x47, 0x6f, 0x4c, 0x61, 0x6e, 0x67, 0x57, 0x65, 0x62, 0x44, 0x65, 0x76, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_primesapi_proto_rawDescOnce sync.Once
	file_primesapi_proto_rawDescData = file_primesapi_proto_rawDesc
)

func file_primesapi_proto_rawDescGZIP() []byte {
	file_primesapi_proto_rawDescOnce.Do(func() {
		file_primesapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_primesapi_proto_rawDescData)
	})
	return file_primesapi_proto_rawDescData
}

var file_primesapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_primesapi_proto_goTypes = []interface{}{
	(*PrimesApiRequest)(nil),  // 0: primes_api.PrimesApiRequest
	(*PrimesApiResponse)(nil), // 1: primes_api.PrimesApiResponse
}
var file_primesapi_proto_depIdxs = []int32{
	0, // 0: primes_api.PrimesAPIService.Primes:input_type -> primes_api.PrimesApiRequest
	1, // 1: primes_api.PrimesAPIService.Primes:output_type -> primes_api.PrimesApiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_primesapi_proto_init() }
func file_primesapi_proto_init() {
	if File_primesapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_primesapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimesApiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primesapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimesApiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_primesapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_primesapi_proto_goTypes,
		DependencyIndexes: file_primesapi_proto_depIdxs,
		MessageInfos:      file_primesapi_proto_msgTypes,
	}.Build()
	File_primesapi_proto = out.File
	file_primesapi_proto_rawDesc = nil
	file_primesapi_proto_goTypes = nil
	file_primesapi_proto_depIdxs = nil
}
